export enum HW5_Events {
    PLAYER_MOVE = "PlayerMove",
    PLAYER_JUMP = "PlayerJump",
    PLAYER_HIT_SWITCH = "PlayerHitSwitch",
    PLAYER_HIT_KEY = "PlayerHitKey",
    BALLOON_POPPED = "BalloonPopped",
    PLAYER_ENTERED_LEVEL_END = "PlayerEnteredLevelEnd",
    PLAYER_HIT_SPECIAL_ITEM = "PlayerHitSpecialItem",
    LEVEL_START = "LevelStart",
    LEVEL_END = "LevelEnd",
    PLAYER_KILLED = "PlayerKilled",
    SUIT_COLOR_CHANGE = "SuitColorChange",
    TOMAIN = "ToMain",
    TOSELECT = "ToSelect",
    TOABOUT = "ToAbout",
    TOCONTROLS = "ToControls",
}